USE Mblix;

CREATE TABLE movie_mbti (
  movie_id INTEGER NOT NULL PRIMARY KEY, 
  movie_name VARCHAR(128) NOT NULL,

  ENFJ MEDIUMINT UNSIGNED, ENFP MEDIUMINT UNSIGNED, ENTJ MEDIUMINT UNSIGNED, ENTP MEDIUMINT UNSIGNED,
  ESFJ MEDIUMINT UNSIGNED, ESFP MEDIUMINT UNSIGNED, ESTJ MEDIUMINT UNSIGNED, ESTP MEDIUMINT UNSIGNED,
  INFJ MEDIUMINT UNSIGNED, INFP MEDIUMINT UNSIGNED, INTJ MEDIUMINT UNSIGNED, INTP MEDIUMINT UNSIGNED,
  ISFJ MEDIUMINT UNSIGNED, ISFP MEDIUMINT UNSIGNED, ISTJ MEDIUMINT UNSIGNED, ISTP MEDIUMINT UNSIGNED
);

SELECT * FROM movie_mbti;

SELECT * FROM movie, (SELECT movie_id FROM movie_mbti ORDER BY ENFJ DESC LIMIT 10) as movies
WHERE id = movies.movie_id;

SELECT * FROM movie_mbti ORDER BY ENFJ DESC LIMIT 10;

DROP TABLE movie_mbti;

SELECT ENFJ FROM movie_mbti WHERE movie_id = 1;

UPDATE movie_mbti SET ENFJ = ENFJ - 1 WHERE movie_id = 1;
